/*******************************************************************************
*
* (C) COPYRIGHT Bombardier Transportation (Signal) Sweden AB, 2002
*
* We reserve all rights in this file and in the information
* contained therein. Reproduction, use or disclosure to third
* parties without express authority is strictly forbidden.
*
* Module name:
*
* %name: NVSHFT_Params.c %
* %created_by: nsyed %
* %version: 1 %
* %created_by: nsyed %
* %date_created: 2017-01-31 16:11 %
* %Creation date of original object: Fri Nov 17 13:55:22 2000 %
*
* Description:
*
*******************************************************************************/
/*******************************************************************************
* Revision History
*
* Version  Date    Sign     Change description
* 4.1.2    160316  gberglun Updated with separate COD parameters. First version of VonfSpec 1.5
* 4.1.1    151125  gberglun Version for P8B configuration
* 2        141124  dthorell Version for P8A configuration
*
* 1.0     130222  wahmad   Initially created
* 1.1     130225  wahmad   Struct is used now instead of global arrays for NVSHFT parameters
* 1.2     130227  wahmad   Few Descriptions added.
* 1.3     130314  wahmad   NVSHFT version1.1 according to parameters updated 1.2
*                          of CFPARAM and 1.4 of IFSATPCU document
* 1.4     130604  wahmad   Lint corrections have been made
* 1.6     140305  anlindel WP020, arn_043#989, updated to conform with CFPARAM 1.5 and
*                          IFSATPCU 1.9.
* 1.7     141002  wahmad   P7B (WP_045+WP_042+45Days Stuff): Q_ETCS new configuration parameter added
* 1.8     170127  nsyed    Adapted to BHP Project (Ver 1.0)
*******************************************************************************/

#include "nvshft.h"

MNT_PARAMS mnt[NOP_MNT] =
{
    {2, "WheelSize1ID"},
    {2, "WheelSize1"},
    {2, "WheelSize2ID"},
    {2, "WheelSize2"},
    {2,"DopplerPulsesPerKmId"},
    {4,"DopplerPulsesPerKm"}
};

RT_PARAMS rt[NOP_RT] =
{
    {2,"LastBTMTestId"},
    {4,"LastBTMTest"},
    {2,"LastBrakeTestId"},
    {4,"LastBrakeTest"},
    {2,"BrakeTestReasonId"},
    {4,"BrakeTestReason"}
};

TYPE_PARAMS typespec[NOP_TYPE]=
{
    { 2, "BalWindowPermilID" },
    { 1, "BalWindowPermil" },
    { 2, "YardSpeedID" },
    { 2, "YardSpeed" },
    { 2, "AtoEnableID" },
    { 4, "AtoEnable"},
    { 2, "TachoPulsesPer10Rev1Id" },
    { 2, "TachoPulsesPer10Rev1" },
    { 2, "TachoPulsesPer10Rev2Id" },
    { 2, "TachoPulsesPer10Rev2" },
    { 2, "BalAntennaPosEndID" },
    { 2, "BalAntennaPosEnd" },
    { 2, "BalAntennaPosFrontID" },
    { 2, "BalAntennaPosFront" },
    { 2,"TrainCfgTicTimeoutId" },
    { 2,"TrainCfgTicTimeout" },
    { 2,"CodSensorConfigId" },
    { 1,"CodSensorConfig" },
    { 2,"TractionControlId" },
    { 1,"TractionControl" },
    { 2,"MinDopplerSpeedId" },
    { 2,"MinDopplerSpeed" },
    { 2,"MaxDopplerSpeedId" },
    { 2,"MaxDopplerSpeed" },
    { 2,"MaxDopplerAccelId" },
    { 2,"MaxDopplerAccel" },
    { 2,"DopplerPulsePrecId" },
    { 1,"DopplerPulsePrec" },
    { 2,"BrakeTestExecTimeId" },
    { 2,"BrakeTestExecTime" },
    { 2,"Tacho1DirectionId" },
    { 1,"Tacho1Direction" },
    { 2,"Tacho2DirectionId" },
    { 1,"Tacho2Direction" },
    { 2,"LocoTypeId" },
    { 1,"LocoType" },
    { 2,"CabinConfigurationId" },
    { 1,"CabinConfiguration" },
    { 2,"EsaInputAvailId" },
    { 4,"ESAInputAvail" },
    { 2,"SbAvailId" },
    { 4,"SbAvail" },
    { 2,"BrakeType1ParamA1Id" },
    { 2,"BrakeType1ParamA1" },
    { 2,"BrakeType2ParamA1Id" },
    { 2,"BrakeType2ParamA1" },
    { 2,"BrakeType3ParamA1Id" },
    { 2,"BrakeType3ParamA1" },
    { 2,"BrakeType1ParamA2Id" },
    { 2,"BrakeType1ParamA2" },
    { 2,"BrakeType2ParamA2Id" },
    { 2,"BrakeType2ParamA2" },
    { 2,"BrakeType3ParamA2Id" },
    { 2,"BrakeType3ParamA2" },
    { 2,"BrakeType1ParamA3Id" },
    { 2,"BrakeType1ParamA3" },
    { 2,"BrakeType2ParamA3Id" },
    { 2,"BrakeType2ParamA3" },
    { 2,"BrakeType3ParamA3Id" },
    { 2,"BrakeType3ParamA3" },
    { 2,"BrakeType1ParamB1Id" },
    { 2,"BrakeType1ParamB1" },
    { 2,"BrakeType2ParamB1Id" },
    { 2,"BrakeType2ParamB1" },
    { 2,"BrakeType3ParamB1Id" },
    { 2,"BrakeType3ParamB1" },
    { 2,"BrakeType1ParamB2Id" },
    { 2,"BrakeType1ParamB2" },
    { 2,"BrakeType2ParamB2Id" },
    { 2,"BrakeType2ParamB2" },
    { 2,"BrakeType3ParamB2Id" },
    { 2,"BrakeType3ParamB2" },
    { 2,"BrakeType1ParamB3Id" },
    { 2,"BrakeType1ParamB3" },
    { 2,"BrakeType2ParamB3Id" },
    { 2,"BrakeType2ParamB3" },
    { 2,"BrakeType3ParamB3Id" },
    { 2,"BrakeType3ParamB3" },
    { 2,"BrakeType1ParamV1Id" },
    { 2,"BrakeType1ParamV1" },
    { 2,"BrakeType2ParamV1Id" },
    { 2,"BrakeType2ParamV1" },
    { 2,"BrakeType3ParamV1Id" },
    { 2,"BrakeType3ParamV1" },
    { 2,"BrakeType1ParamV2Id" },
    { 2,"BrakeType1ParamV2" },
    { 2,"BrakeType2ParamV2Id" },
    { 2,"BrakeType2ParamV2" },
    { 2,"BrakeType3ParamV2Id" },
    { 2,"BrakeType3ParamV2" },
    { 2,"BrakeType1LambdaMinId" },
    { 1,"BrakeType1LambdaMin" },
    { 2,"BrakeType2LambdaMinId" },
    { 1,"BrakeType2LambdaMin" },
    { 2,"BrakeType3LambdaMinId" },
    { 1,"BrakeType3LambdaMin" },
    { 2,"BrakeType1LambdaMaxId" },
    { 1,"BrakeType1LambdaMax" },
    { 2,"BrakeType2LambdaMaxId" },
    { 1,"BrakeType2LambdaMax" },
    { 2,"BrakeType3LambdaMaxId" },
    { 1,"BrakeType3LambdaMax" },
    { 2,"MaxAccelerationId" },
    { 2,"MaxAcceleration" },
    { 2,"MaxDecelerationId" },
    { 2,"MaxDeceleration" },
    { 2,"MaxHelperGradTargId" },
    { 1,"MaxHelperGradTarg" },
    { 2,"MinHelperGradTargDstId" },
    { 4,"MinHelperGradTargDst" },
    { 2,"TractionCutOffDelayId" },
    { 1,"TractionCutOffDelay" },
    { 2,"upperSpeedSbDecId" },
    { 2,"upperSpeedSbDec" },
    { 2,"lowerSpeedSbDecId" },
    { 2,"lowerSpeedSbDec" },
    { 2,"upperSpeedEbDecId" },
    { 2,"upperSpeedEbDec" },
    { 2,"lowerSpeedEbDecId" },
    { 2,"lowerSpeedEbDec" },
    { 2,"timeSbv0Id" },
    { 2,"timeSbv0" },
    { 2,"timeEbv0Id" },
    { 2,"timeEbv0" },
    { 2,"BrakeType1ParamT1SBId" },
    { 2,"BrakeType1ParamT1SB" },
    { 2,"BrakeType1ParamT2SBId" },
    { 2,"BrakeType1ParamT2SB" },
    { 2,"BrakeType1ParamT3SBId" },
    { 2,"BrakeType1ParamT3SB" },
    { 2,"BrakeType2ParamT1SBId" },
    { 2,"BrakeType2ParamT1SB" },
    { 2,"BrakeType2ParamT2SBId" },
    { 2,"BrakeType2ParamT2SB" },
    { 2,"BrakeType2ParamT3SBId" },
    { 2,"BrakeType2ParamT3SB" },
    { 2,"BrakeType3ParamT1SBId" },
    { 2,"BrakeType3ParamT1SB" },
    { 2,"BrakeType3ParamT2SBId" },
    { 2,"BrakeType3ParamT2SB" },
    { 2,"BrakeType3ParamT3SBId" },
    { 2,"BrakeType3ParamT3SB" },
    { 2,"DefaultBrakeDelayId" },
    { 2,"DefaultBrakeDelay" },
    { 2,"DefaultBrakeabilityId" },
    { 2,"DefaultBrakeability" },
    { 2,"EBMarginAddedId" },
    { 1,"EBMarginAdded" },
    { 2,"EbPrPropagationSpeedId" },
    { 2,"EbPrPropagationSpeed" },
    { 2,"vNomMarginId"},
    { 1,"vNomMargin"},
    { 2,"BrakeType1ParamT1EBId" },
    { 2,"BrakeType1ParamT1EB" },
    { 2,"BrakeType1ParamT2EBId" },
    { 2,"BrakeType1ParamT2EB" },
    { 2,"BrakeType1ParamT3EBId" },
    { 2,"BrakeType1ParamT3EB" },
    { 2,"BrakeType2ParamT1EBId" },
    { 2,"BrakeType2ParamT1EB" },
    { 2,"BrakeType2ParamT2EBId" },
    { 2,"BrakeType2ParamT2EB" },
    { 2,"BrakeType2ParamT3EBId" },
    { 2,"BrakeType2ParamT3EB" },
    { 2,"BrakeType3ParamT1EBId" },
    { 2,"BrakeType3ParamT1EB" },
    { 2,"BrakeType3ParamT2EBId" },
    { 2,"BrakeType3ParamT2EB" },
    { 2,"BrakeType3ParamT3EBId" },
    { 2,"BrakeType3ParamT3EB" },
    { 2,"TicInitToRunTimeoutId" },
    { 2,"TicInitToRunTimeout" },
    { 2,"RangeMinBP1Id" },
    { 2,"RangeMinBP1" },
    { 2,"RangeMaxBP1Id" },
    { 2,"RangeMaxBP1" },
    { 2,"RangeMinBP2Id" },
    { 2,"RangeMinBP2" },
    { 2,"RangeMaxBP2Id" },
    { 2,"RangeMaxBP2" },
    { 2,"MaxEbApplyFbId" },
    { 2,"MaxEbApplyFb" },
    { 2,"MinEbReleaseFbId" },
    { 2,"MinEbReleaseFb" },
    { 2,"MaxEbFbDiffId" },
    { 2,"MaxEbFbDiff" },
    { 2,"EbFbInaccuracyId" },
    { 2,"EbFbInaccuracy" },
    { 2,"EbFbSignalStatusId" },
    { 1,"EbFbSignalStatus" },
    { 2,"RailRoadInputAvailId" },
    { 4,"RailRoadInputAvail" },
    { 2,"EbCutOutConfiguredId" },
    { 4,"EbCutOutConfigured" },
    { 2,"MaxEbFbDiffTimeoutId" },
    { 1,"MaxEbFbDiffTimeout" },
    { 2,"EcpbMinPercBrakeCarsId" },
    { 1,"ECPBMinPercBrakeCars" },
    { 2,"NonLeadingLocoInputId" },
    { 4,"NonLeadingLocoInput" },
    { 2,"TimsMinBPLocoId" },
    { 2,"TimsMinBPLoco" },
    { 2,"TimsMinBPLastCarId" },
    { 2,"TimsMinBPLastCar" },
    { 2,"TcoOrderAndTCOFbId" },
    { 1,"TcoOrderAndTCOFb" },
    { 2,"EbFeedbackTimeoutId" },
    { 2,"EbFeedbackTimeout" },
    { 2,"TcoFeedbackTimeoutId" },
    { 2,"TcoFeedbackTimeout" },
    { 2,"UseEbTcoFbBrakeTestId" },
    { 1,"UseEbTcoFbBrakeTest" },
    { 2,"LcsSampleSpeedDiffId" },
    { 1,"LcsSampleSpeedDiff" },
    { 2,"LcsMaxSample" },
    { 1,"LcsMaxSample" },
    { 2,"EcpbCarInBrakeCalcId" },
    { 1,"EcpbCarInBrakeCalc" },
    { 2,"BPDeltaRapidLossId" },
    { 2,"BPDeltaRapidLoss" },
    { 2,"BPTimeRapidLossId" },
    { 1,"BPTimeRapidLoss" },
    { 2,"TimsEcbpTimeOutId" },
    { 1,"TimsEcbpTimeOut" },
    { 2,"TimsEotTimeOutId" },
    { 1,"TimsEotTimeOut" },
    { 2,"TimsLengthMarginId" },
    { 1,"TimsLengthMargin" },
    { 2,"SbPrPropagationSpeedId" },
    { 2,"SbPrPropagationSpeed" },
    { 2,"MaxExtRevDistanceId" },
    { 2,"MaxExtRevDistance" },
    { 2,"MaxExtRevSpeedId" },
    { 2,"MaxExtRevSpeed" },
    { 2,"MinApproachSpeedId" },
    { 2,"MinApproachSpeed" },
    { 2,"OBRDLengthMarginId" },
    { 1,"OBRDLengthMargin" },
    { 2,"OBRDBrakeTestPrId" },
    { 2,"OBRDBrakeTestPr" },
    { 2,"OBRDMaxReportTimeId"},
    { 1,"OBRDMaxReportTime"},
    { 2,"BPStabilizeMarginId"},
    { 2,"BPStabilizeMargin"}
};

INSTANCE_PARAMS instance[NOP_INSTANCE]=
{
  {2,"RadioIdID"},
  {2,"RadioId"}
};

COMMON_PARAMS common[NOP_COMMON] = {
    {2, "NjruIpID"},
    {1, "NjruIp1"},
    {1, "NjruIp2"},
    {1, "NjruIp3"},
    {1, "NjruIp4"},
    {2, "NjruPortID"},
    {2, "NjruPort"},
    {2, "BdsPortID"},
    {2, "BdsPort"},
    {2, "ConsolePortID"},
    {2, "ConsolePort"},
    {2, "NjruLevelID"},
    {1, "NjruLevel"},
    {2, "BdsLevelID"},
    {1, "BdsLevel"},
    {2, "RuIpID" },
    {1, "RuIp1"},
    {1, "RuIp2"},
    {1, "RuIp3"},
    {1, "RuIp4"},
    {2, "RuPortID"},
    {2, "RuPort"},
    {2, "RuLogDynValuePeriodID"},
    {1, "RuLogDynValuePeriod"},
    {2, "RuLogValueDiffID"},
    {2, "RuLogValueDiff"},
    {2, "BalNidCID"},
    {2, "BalNidC"},
    {2, "SiteIdID"},
    {1, "SiteId"},
    {2, "RadioTimeOutID"},
    {1, "RadioTimeOut"},
    {2, "RadioTimeOutSbID"},
    {1, "RadioTimeOutSb"},
    {2, "BalSearchDistanceID"},
    {2, "BalSearchDistance"},
    {2, "BalSearchSpeedID"},
    {2, "BalSearchSpeed"},
    {2, "BalWindowMinID"},
    {2, "BalWindowMin"},
    {2, "RevSupMarginNormID"},
    {2, "RevSupMarginNorm"},
    {2, "RevSupMarginShuntID"},
    {2, "RevSupMarginShunt"},
    {2, "RollAwayMarginID"},
    {2, "RollAwayMargin"},
    {2, "EnableDiagnosticsId" },
    {4, "EnableDiagnostics" },
    {2, "MaxWheelSizeErrorID" },
    {1, "MaxWheelSizeError" },
    {2, "RevSupMarginFreeRollId"},
    {2, "RevSupMarginFreeRoll"},
    {2, "MinSpeedMarginWarnID"},
    {2, "MinSpeedMarginWarn"},
    {2, "MinSpeedMarginSBID"},
    {2, "MinSpeedMarginSB"},
    {2, "MinSpeedMarginEBID"},
    {2, "MinSpeedMarginEB"},
    {2, "MaxSpeedMarginWarnID"},
    {2, "MaxSpeedMarginWarn"},
    {2, "MaxSpeedMarginSBID"},
    {2, "MaxSpeedMarginSB"},
    {2, "MaxSpeedMarginEBID"},
    {2, "MaxSpeedMarginEB"},
    {2, "SpeedMarginWarnID"},
    {2, "SpeedMarginWarn"},
    {2, "SpeedMarginSBID"},
    {2, "SpeedMarginSB"},
    {2, "SpeedMarginEBID"},
    {2, "SpeedMarginEB"},
    {2, "FwToSwDelayId"},
    {2, "FwToSwDelay"},
    {2, "SwToSBDelayId"},
    {2, "SwToSBDelay"},
    {2, "SbToEbDelayID"},
    {2, "SbToEbDelay"},
    {2, "EffectiveEbDelayID"},
    {2, "EffectiveEbDelay"},
    {2,"OpcMajorVersionId"},
    {1,"OpcMajorVersion"},
    {2,"OpcMiddleVersionId"},
    {1,"OpcMiddleVersion"},
    {2,"OpcMinorVersionId"},
    {1,"OpcMinorVersion"},
    {2,"AnalyzerIFPortID"},
    {2,"AnalyzerIFPort"},
    {2,"SendCycleAIFID"},
    {1,"SendCycleAIF"},
    {2,"SecBalSearchDistanceId"},
    {2,"SecBalSearchDistance"},
    {2,"EventKeepActiveTimeId"},
    {1,"EventKeepActiveTime"},
    {2,"BTMTestNotifyId"},
    {2,"BTMTestNotify"},
    {2,"BTMTestMandatoryId"},
    {2,"BTMTestMandatory"},
    {2,"BrakeTestNotifyId"},
    {2,"BrakeTestNotify"},
    {2,"BrakeTestMandatoryId"},
    {2,"BrakeTestMandatory"},
    {2,"MaxTimeAOSRunId"},
    {2,"MaxTimeAOSRun"},
    {2,"IntRelaysTimeoutId"},
    {2,"IntRelaysTimeout"},
    {2,"SbExpectedDecLimitId"},
    {1,"SbExpectedDecLimit"},
    {2,"EbExpectedDecLimitId"},
    {1,"EbExpectedDecLimit"},
    {2,"RadioTimeOutYardModeId"},
    {1,"RadioTimeOutYardMode"},
    {2,"maxLowDecInRowSBId"},
    {2,"maxLowDecInRowSB"},
    {2,"maxLowDecAccumSBId"},
    {2,"maxLowDecAccumSB"},
    {2,"maxLowDecInRowEBId"},
    {2,"maxLowDecInRowEB"},
    {2,"maxLowDecAccumEBId"},
    {2,"maxLowDecAccumEB"},
    {2,"StandstillActiveTimeId" },
    {1,"StandstillActiveTime" },
    {2,"TimsManualConfTimeId"},
    {1,"TimsManualConfTime"},
    {2,"TimsSensorTimeDiffId"},
    {1,"TimsSensorTimeDiff"},
    {2,"ReleaseSpeedId"},
    {2,"ReleaseSpeed"},
    {2,"DepartureWarningId"},
    {1,"DepartureWarning"},
    {2,"TimeSyncSrvVersion1Id"},
    {1,"TimeSyncSrvVersion1"},
    {2,"TimeSyncSrvVersion2Id"},
    {1,"TimeSyncSrvVersion2"},
    {2,"TimeSyncSrvVersion3Id"},
    {1,"TimeSyncSrvVersion3"},
    {2,"TimeSyncSrvVersion4Id"},
    {1,"TimeSyncSrvVersion4"}
};

CFG_DISP_PARAMS cfg_disp[NOP_CFG_DISP] =
{
    {2, "NjruIpID"},
    {1, "NjruIp1"},
    {1, "NjruIp2"},
    {1, "NjruIp3"},
    {1, "NjruIp4"},
    {2, "NjruPortID"},
    {2, "NjruPort"},
    {2, "BdsPortID"},
    {2, "BdsPort"},
    {2, "ConsolePortID"},
    {2, "ConsolePort"},
    {2, "NjruLevelID"},
    {1, "NjruLevel"},
    {2, "BdsLevelID"},
    {1, "BdsLevel"},
    {2, "TCC1PortID"},
    {2, "TCC1Port"},
    {2, "TCC2PortID"},
    {2, "TCC2Port"},
    {2, "TCC3PortID"},
    {2, "TCC3Port"},
    {2, "DMI1IpID"},
    {1, "DMI1Ip1"},
    {1, "DMI1Ip2"},
    {1, "DMI1Ip3"},
    {1, "DMI1Ip4"},
    {2, "DMI2IpID"},
    {1, "DMI2Ip1"},
    {1, "DMI2Ip2"},
    {1, "DMI2Ip3"},
    {1, "DMI2Ip4"},
    {2, "DMIPortID"},
    {2, "DMIPort"},
    {2, "LIGPortID"},
    {2, "LIGPort"},
    {2, "LIGIpID"},
    {1, "LIGIp1"},
    {1, "LIGIp2"},
    {1, "LIGIp3"},
    {1, "LIGIp4"},
    {2, "RemoteOPCIpID"},
    {1, "RemoteOPCIp1"},
    {1, "RemoteOPCIp2"},
    {1, "RemoteOPCIp3"},
    {1, "RemoteOPCIp4"},
    {2, "RemoteOPCPortID"},
    {2, "RemoteOPCPort"},
    {2, "LocalOPCPortID"},
    {2, "LocalOPCPort"},
    {2, "OBRDPortID" },
    {2, "OBRDPort" }
};

S_INT parameterSize_MNT[NOP_MNT];

S_INT parameterSize_RT[NOP_RT];

S_INT parameterSize_COMMON[NOP_COMMON];

S_INT parameterSize_INSTANCE[NOP_INSTANCE];

S_INT parameterSize_TYPE[NOP_TYPE];

S_INT parameterSize_CFG_DISP[NOP_CFG_DISP];

US_CHAR* parameterName_MNT[NOP_MNT];

US_CHAR* parameterName_RT[NOP_RT];

US_CHAR* parameterName_COMMON[NOP_COMMON];

US_CHAR* parameterName_CFG_DISP[NOP_CFG_DISP];

US_CHAR* parameterName_INSTANCE[NOP_INSTANCE];

US_CHAR* parameterName_TYPE[NOP_TYPE];
